### ISSUE TITLE
I get this error when trying to download a TMX file.

### ISSUE THREAD

**Issue by Hammyhamm89** [Helsinki-NLP/OPUS#2]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>InvalidTenantName</Code>
<RequestId>tx0000000000000015f3683-00639335f8-406c1e12-allas-prod-kaj</RequestId>
<HostId>406c1e12-allas-prod-kaj-cpouta-production</HostId>
</Error>

**Comment by jorgtied** [comment]
Is this still the case? What is the exact document that you're trying to download?

**Comment by Hammyhamm89** [comment]
Sorry for the late reply but it's fixed now! :D.
